apiVersion: v1
kind: Namespace
metadata:
  name: apps-blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app.kubernetes.io/name: blog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog
    spec:
      containers:
        - image: ghcr.io/augustfengd/augustfeng.app/blog
          name: blog
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app.kubernetes.io/name: blog
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: blog
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blog.augustfeng.app
spec:
  routes:
    - match: Host(`blog.augustfeng.app`)
      kind: Rule
      services:
        - name: blog
          port: 80
          kind: Service
  entryPoints:
    - websecure
  tls:
    secretName: blog.augustfeng.app
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog.augustfeng.app
spec:
  dnsNames:
    - blog.augustfeng.app
  secretName: blog.augustfeng.app
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
