---
- name: gpg
  hosts: all
  become: true
  tasks:
    - name: asc
      ansible.builtin.get_url:
        url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
        dest: /etc/apt/trusted.gpg.d/jellyfin.asc
        mode: '0644'
      notify: dearmor
  handlers:
    - name: dearmor
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/trusted.gpg.d/jellyfin.gpg /etc/apt/trusted.gpg.d/jellyfin.asc
- name: apt
  hosts: all
  become: true
  tasks:
    - name: Add Jellyfin deb822 repository
      ansible.builtin.deb822_repository:
        name: jellyfin
        types: [deb]
        uris: https://repo.jellyfin.org/ubuntu
        suites: [noble]
        components: [main]
        architectures: [amd64]
        signed_by: /etc/apt/trusted.gpg.d/jellyfin.gpg
        state: present
- name: jellyfin
  hosts: all
  become: true
  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache: yes
    - name: install
      ansible.builtin.apt:
        name: jellyfin
        state: present
