- name: nginx
  hosts: all
  become: true
  tasks:
    - name: install
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: laptop2022.conf
      ansible.builtin.copy:
        src: nginx/laptop2022.conf
        dest: /etc/nginx/conf.d/laptop2022.conf
      notify: nginx
  handlers:
    - name: nginx
      ansible.builtin.systemd_service:
        state: restarted
        name: nginx
