---
- name: arr
  hosts: all
  become: true
  tasks:
    - name: Create group 'media'
      ansible.builtin.group:
        name: media
        system: yes
    - name: augustfeng
      ansible.builtin.user:
        name: augustfeng
        append: yes
        groups:
          - media
- name: jellyfin - gpg
  hosts: all
  become: true
  tasks:
    - name: asc
      ansible.builtin.get_url:
        url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
        dest: /etc/apt/trusted.gpg.d/jellyfin.asc
        mode: '0644'
      notify: dearmor
  handlers:
    - name: dearmor
      ansible.builtin.command:
        cmd: gpg --dearmor --output /etc/apt/trusted.gpg.d/jellyfin.gpg /etc/apt/trusted.gpg.d/jellyfin.asc
- name: jellyfin
  hosts: all
  become: true
  tasks:
    - name: Add Jellyfin deb822 repository
      ansible.builtin.deb822_repository:
        name: jellyfin
        types: [deb]
        uris: https://repo.jellyfin.org/ubuntu
        suites: [noble]
        components: [main]
        architectures: [amd64]
        signed_by: /etc/apt/trusted.gpg.d/jellyfin.gpg
        state: present
    - name: update
      ansible.builtin.apt:
        update_cache: yes
    - name: install
      ansible.builtin.apt:
        name: jellyfin
        state: present
    - name: media
      ansible.builtin.user:
        name: jellyfin
        append: yes
        groups:
          - media
- name: sonarr
  hosts: all
  become: true
  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache: yes
    - name: Create 'sonarr' home
      ansible.builtin.file:
        path: /home/sonarr
        state: directory
        owner: sonarr
        group: media
    - name: Create user 'sonarr'
      ansible.builtin.user:
        name: sonarr
        group: media
        system: yes
    - name: Create datadir
      ansible.builtin.file:
        path: /var/lib/sonarr
        state: directory
        owner: sonarr
        group: media
        mode: '0755'
    - name: Download
      get_url:
        url: "https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux&arch=x64"
        dest: /tmp/sonarr.tar.gz
        mode: '0644'
    - name: Extract Sonarr to /opt/Sonarr
      unarchive:
        src: /tmp/sonarr.tar.gz
        dest: /opt
        remote_src: yes
    - name: sonarr.service
      ansible.builtin.copy:
        src: usenet/sonarr.service
        dest: /etc/systemd/system/sonarr.service
    - name: sonarr
      ansible.builtin.systemd_service:
        name: sonarr
        state: started
        enabled: true
- name: radarr
  hosts: all
  become: true
  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache: yes
    - name: Create 'radarr' home
      ansible.builtin.file:
        path: /home/radarr
        state: directory
        owner: sonarr
        group: media
    - name: Create user 'radarr'
      ansible.builtin.user:
        name: radarr
        group: media
        system: yes
    - name: Create datadir
      ansible.builtin.file:
        path: /var/lib/radarr
        state: directory
        owner: radarr
        group: media
        mode: '0755'
    - name: Download
      get_url:
        url: 'http://radarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64'
        dest: /tmp/radarr.tar.gz
        mode: '0644'
    - name: Extract Radarr to /opt/Radarr
      unarchive:
        src: /tmp/radarr.tar.gz
        dest: /opt
        remote_src: yes
    - name: radarr.service
      ansible.builtin.copy:
        src: usenet/radarr.service
        dest: /etc/systemd/system/radarr.service
    - name: radarr
      ansible.builtin.systemd_service:
        name: radarr
        state: started
        enabled: true
- name: transmission
  hosts: all
  become: true
  tasks:
    # XXX: create debian-transmission and bypass the check guard in the transmission-daemon's postint
    - name: user
      ansible.builtin.user:
        name: debian-transmission
        home: /var/lib/transmission-daemon
        system: yes
    # XXX: the postint expects this group even if we're not going to use it.
    - name: Create group 'debian-transmission'
      ansible.builtin.group:
        name: debian-transmission
        system: yes
    - name: install
      ansible.builtin.apt:
        name: transmission-daemon
        state: present
    # XXX: rewrite the permissions configured by postint
    - name: permissions
      ansible.builtin.file:
        path: "{{ item }}"
        group: media
      loop:
        - /var/lib/transmission-daemon/.config/transmission-daemon
        - /var/lib/transmission-daemon/downloads
        - /etc/transmission-daemon/settings.json
        - /etc/transmission-daemon
    - name: /etc/systemd/system/transmission-daemon.service.d
      ansible.builtin.file:
        path: /etc/systemd/system/transmission-daemon.service.d
        state: directory
        owner: root
        group: root
    # hack: https://askubuntu.com/a/1528158
    - name: transmission-daemon
      ansible.builtin.copy:
        src: usenet/transmission.conf
        dest: /etc/systemd/system/transmission-daemon.service.d/override.conf
      notify: systemd
    # TODO: update the umask in /etc/transmission-daemon/settings.json to 002.
  handlers:
    - name: systemd
      ansible.builtin.systemd_service:
        state: restarted
        name: transmission-daemon
- name: SABnzbd
  hosts: all
  become: true
  tasks:
    - name: Add jcfp/nobetas PPA
      ansible.builtin.apt_repository:
        repo: ppa:jcfp/nobetas
        state: present
    - name: Update APT cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
    - name: Install sabnzbdplus
      ansible.builtin.apt:
        name: sabnzbdplus
        state: present
    - name: Create user 'sabnzbdplus'
      ansible.builtin.user:
        name: sabnzbdplus
        group: media
        system: yes
    - name: sabnzbdplus
      ansible.builtin.copy:
        src: usenet/sabnzbdplus.conf
        dest: /etc/default/sabnzbdplus
    - name: umask
      community.general.ini_file:
        path: /home/sabnzbdplus/.sabnzbd/sabnzbd.ini
        section: misc
        option: permissions
        value: 775
    - name: Reload systemd and restart sabnzbdplus service
      ansible.builtin.systemd:
        name: sabnzbdplus
        state: restarted
        daemon_reload: yes
