apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: ubuntu
          command:
            - bash
          args:
            - -c
            - "trap : TERM INT; sleep infinity & wait"
