apiVersion: skaffold/v4beta6
kind: Config
manifests:
  rawYaml:
    - k8s/rbac.yaml
  hooks:
    before:
    - host:
        command: ["make", "k8s/rbac.yaml"]
deploy:
  kubectl: {}
---
apiVersion: skaffold/v4beta6
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ghcr.io/augustfengd/augustfeng.app/domain
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/workload.yaml
  hooks:
    before:
    - host:
        command: ["make", "k8s/workload.yaml"]
deploy:
  kubectl: {}
