apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: domain
build:
  artifacts:
    - image: ghcr.io/augustfengd/augustfeng.app/domain
      docker:
        dockerfile: Dockerfile
manifests:
  hooks:
    before:
    - host:
        command: ["make", "k8s/manifests.yaml"]
