name: apps/blog
"on":
  push:
    branches: main
    paths:
      - apps/blog/**
concurrency: apps/blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: cd apps/blog ; make
    - uses: actions/upload-artifact@v4
      with:
        name: blog
        path: apps/blog/build/
  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: blog
        path: apps/blog/build/
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: "arn:aws:iam::449594425026:role/GitHubActionsAugustfengApp"
    - run: "aws s3 cp apps/blog/build/public s3://augustfeng-app/blog/ --recursive"
