name: cloud
"on":
  push:
    branches: main
    paths:
      - cloud/**
  pull_request:
    branches: main
    paths:
      - cloud/**
concurrency: augustfeng.app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: make
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: make
      - name: Archive Build
        run: tar cvz build | age -r age13x2cud63r8fr9qjlqdxjcuahlzxh3rvpgx6vgl263dkk2ghgpckqrg5r7p > build.tar.gz.age
      - uses: actions/upload-artifact@v3
        with:
          name: build.tar.gz.age
          path: build.tar.gz.age
      - name: Archive Secrets
        run: tar cvz cloud/secrets | age -r age13x2cud63r8fr9qjlqdxjcuahlzxh3rvpgx6vgl263dkk2ghgpckqrg5r7p > secrets.tar.gz.age
      - uses: actions/upload-artifact@v3
        with:
          name: secrets.tar.gz.age
          path: secrets.tar.gz.age
    container:
      image: ghcr.io/augustfengd/toolchain:latest
  configure:
    name: terraform cloud
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: make
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: make
      - name: Configure workspace
        run: cue configure ./cloud/augustfeng.app:terraform
    container:
      image: ghcr.io/augustfengd/toolchain:latest
  terraform-plan:
    name: terraform plan
    needs:
      - build
      - configure
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: make
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: make
      - id: init
        name: Terraform Init
        run: terraform init
        working-directory: build/terraform
      - id: plan
        name: Terraform Plan
        run: terraform plan
        working-directory: build/terraform
    container:
      image: ghcr.io/augustfengd/toolchain:latest
  terraform-apply:
    name: terraform apply
    needs:
      - build
      - configure
    runs-on: ubuntu-latest
    if: github.event_name =='push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: make
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: make
      - id: init
        name: Terraform Init
        run: terraform init
        working-directory: build/terraform
      - id: apply
        name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: build/terraform
    container:
      image: ghcr.io/augustfengd/toolchain:latest
  argocd-apply:
    name: argocd (apply)
    needs:
      - terraform-apply
      - build
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    if: github.event_name =='push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: make
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: make
      - name: gcloud-auth
        run: |-
          /opt/google-cloud-sdk/bin/gcloud auth login --cred-file <(printf '%s
          ' ${GOOGLE_CREDENTIALS})
      - name: gcloud-container-clusters
        run: /opt/google-cloud-sdk/bin/gcloud container clusters get-credentials augustfeng-app --zone us-east1-b --project augustfengd
      - run: kubectl create ns argocd --dry-run=client -oyaml | kubectl apply -f -
      - run: kubectl -n argocd apply -f build/argocd/crds
      - run: kubectl -n argocd apply -f build/argocd
    container:
      image: ghcr.io/augustfengd/toolchain:latest
  argocd-diff:
    name: argocd (diff)
    needs:
      - build
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        if: env.GOOGLE_CREDENTIALS != ''
        uses: actions/checkout@v3
      - name: make
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        if: env.GOOGLE_CREDENTIALS != ''
        run: make
      - if: env.GOOGLE_CREDENTIALS != ''
        name: gcloud-auth
        run: |-
          /opt/google-cloud-sdk/bin/gcloud auth login --cred-file <(printf '%s
          ' ${GOOGLE_CREDENTIALS})
      - if: env.GOOGLE_CREDENTIALS != ''
        name: gcloud-container-clusters
        run: /opt/google-cloud-sdk/bin/gcloud container clusters get-credentials augustfeng-app --zone us-east1-b --project augustfengd
      - if: env.GOOGLE_CREDENTIALS != ''
        run: kubectl diff -f build/argocd
    container:
      image: ghcr.io/augustfengd/toolchain:latest
