name: cloud
"on":
  push:
    branches: main
    paths:
      - cloud/**
  pull_request:
    branches: main
    paths:
      - cloud/**
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: make
        run: make
  configure:
    needs:
      - build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: Decrypt and convert secrets
        run: cue decrypt && cue convert
        working-directory: cloud/_secrets
      - name: Configure workspace
        run: cue configure ./cloud/augustfeng.app:terraform
  plan:
    needs:
      - build
      - configure
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: make
        run: make
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: build/terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: build/terraform
  apply:
    needs:
      - build
      - configure
    if: github.event_name =='push'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: make
        run: make
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: build/terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: build/terraform
  finish:
    needs:
      - apply
    if: github.event_name =='push'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
