name: cloud'
"on":
  push:
    branches: main
    paths:
      - cloud/**
      - cue.mod/**
      - cue.lib/**
  pull_request:
    branches: main
    paths:
      - cloud/**
      - cue.mod/**
      - cue.lib/**
concurrency: augustfeng.app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    container:
      image: ghcr.io/augustfengd/augustfeng.app/toolchain:latest
  configure:
    name: terraform cloud
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    container:
      image: ghcr.io/augustfengd/augustfeng.app/toolchain:latest
  terraform-plan:
    name: terraform (plan)
    needs:
      - build
      - configure
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    container:
      image: ghcr.io/augustfengd/augustfeng.app/toolchain:latest
  terraform-apply:
    name: terraform (apply)
    needs:
      - build
      - configure
    runs-on: ubuntu-latest
    if: github.event_name =='push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    container:
      image: ghcr.io/augustfengd/augustfeng.app/toolchain:latest
  cluster-services-apply:
    name: cluster services (apply)
    needs:
      - terraform-apply
      - build
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_APPLICATION_CREDENTIALS: application_default_credentials.json
      KUBECONFIG: kubeconfig.yaml
    if: github.event_name =='push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: decrypt secrets
        run: cue decrypt github.com/augustfengd/augustfeng.app/secrets
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - name: import secrets
        run: cue convert github.com/augustfengd/augustfeng.app/secrets
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - name: configure google application credentials
        run: printf '%s' "${GOOGLE_CREDENTIALS}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: application_default_credentials.json
      - name: cue apply github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
        run: cue apply github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
        env:
          KUBECONFIG: kubeconfig.yaml
    container:
      image: ghcr.io/augustfengd/augustfeng.app/toolchain:latest
  cluster-services-diff:
    name: cluster services (diff)
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: decrypt secrets
        run: cue decrypt github.com/augustfengd/augustfeng.app/secrets
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - name: import secrets
        run: cue convert github.com/augustfengd/augustfeng.app/secrets
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - name: configure google application credentials
        run: printf '%s' "${GOOGLE_CREDENTIALS}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GOOGLE_APPLICATION_CREDENTIALS: application_default_credentials.json
      - name: cue diff github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
        run: cue diff github.com/augustfengd/augustfeng.app/cloud/kubernetes/traefik
        env:
          KUBECONFIG: kubeconfig.yaml
    container:
      image: ghcr.io/augustfengd/augustfeng.app/toolchain:latest
