name: cloud
"on":
  push:
    branches: main
    paths:
      - cloud/**
  pull_request:
    branches: main
    paths:
      - cloud/**
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: make
        run: make
  configure:
    needs:
      - build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: Decrypt and convert secrets
        run: cue decrypt && cue convert
        working-directory: cloud/secrets
      - name: Configure workspace
        run: cue configure ./cloud/augustfeng.app:terraform
  plan:
    needs:
      - build
      - configure
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: make
        run: make
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: build/terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: build/terraform
  apply:
    needs:
      - build
      - configure
    if: github.event_name =='push'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        name: make
        run: make
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: build/terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: build/terraform
  argocd:
    needs:
      - apply
    if: github.event_name =='push'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/augustfengd/toolchain:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        name: gcloud-auth
        run: |-
          gcloud auth login --cred-file <(printf '%s
          ' ${GOOGLE_CREDENTIALS})
        shell: zsh {0}
      - env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: "True"
        name: gcloud-kubectl
        run: gcloud container clusters get-credentials augustfeng-app --zone us-east1-b --project augustfengd
        shell: zsh {0}
      - name: build
        run: jsonnet -m build/argocd -c cloud/argocd/argocd.jsonnet --tla-str fqdn=argocd.augustfeng.app --tla-code-file argocdCmpSecrets=cloud/secrets/sops-secrets.json
